//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPU.DORMITORY.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DPU.DORMITORY.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ทำรายการ.
        /// </summary>
        internal static string MSG_CHECKIN_DATE {
            get {
                return ResourceManager.GetString("MSG_CHECKIN_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ย้ายออก.
        /// </summary>
        internal static string MSG_CHECKOUT_DATE {
            get {
                return ResourceManager.GetString("MSG_CHECKOUT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีข้อมูลอยู่แล้ว {0} ไม่สามารถบันทึกซ้ำได้.
        /// </summary>
        internal static string MSG_DONT_INSERT_EXIST {
            get {
                return ResourceManager.GetString("MSG_DONT_INSERT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีข้อมูลลูกค้าในระบบแล้ว.
        /// </summary>
        internal static string MSG_EXIST_CUSTOMER_NUMBER {
            get {
                return ResourceManager.GetString("MSG_EXIST_CUSTOMER_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ย้ายห้อง.
        /// </summary>
        internal static string MSG_MOVEROOM_DATE {
            get {
                return ResourceManager.GetString("MSG_MOVEROOM_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบผู้พักในห้อง {0}.
        /// </summary>
        internal static string MSG_NO_CUSTOMER_IN_ROOM {
            get {
                return ResourceManager.GetString("MSG_NO_CUSTOMER_IN_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยังไม่ได้ชำระเงิน.
        /// </summary>
        internal static string MSG_PAYMENT_FALSE {
            get {
                return ResourceManager.GetString("MSG_PAYMENT_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชำระเงินแล้ว.
        /// </summary>
        internal static string MSG_PAYMENT_TRUE {
            get {
                return ResourceManager.GetString("MSG_PAYMENT_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกิดข้อผิดพลาดในการบันทึกข้อมูล.
        /// </summary>
        internal static string MSG_SAVE_FAIL {
            get {
                return ResourceManager.GetString("MSG_SAVE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึกข้อมูลเรียบร้อยแล้ว.
        /// </summary>
        internal static string MSG_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถพักเกิน {0} / ห้อง.
        /// </summary>
        internal static string MSG_STAY_OVER_LIMIT {
            get {
                return ResourceManager.GetString("MSG_STAY_OVER_LIMIT", resourceCulture);
            }
        }
    }
}
