//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPU.DORMITORY.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public MENU()
        {
            this.MENU_ROLE = new HashSet<MENU_ROLE>();
        }
    
        public int MENU_ID { get; set; }
        public string MENU_ICON { get; set; }
        public string MENU_NAME { get; set; }
        public string URL_NAVIGATE { get; set; }
        public string MENU_TAG { get; set; }
        public Nullable<int> PREVIOUS_MENU_ID { get; set; }
        public int DISPLAY_ORDER { get; set; }
        public string UPDATE_BY { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    
        public virtual ICollection<MENU_ROLE> MENU_ROLE { get; set; }
    }
}
