//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPU.DORMITORY.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CUSTOMER_FUND
    {
        public int ID { get; set; }
        public Nullable<int> CUS_ID { get; set; }
        public Nullable<int> FUND_ID { get; set; }
        public Nullable<int> FOR_SERVICE_ID { get; set; }
    
        public virtual TB_CUSTOMER TB_CUSTOMER { get; set; }
        public virtual TB_M_FUND TB_M_FUND { get; set; }
        public virtual TB_M_SERVICE TB_M_SERVICE { get; set; }
    }
}
