//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPU.DORMITORY.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CUSTOMER_PROFILE
    {
        public int CUS_ID { get; set; }
        public string ADDR { get; set; }
        public string ROAD { get; set; }
        public string SOI { get; set; }
        public string TAMBON { get; set; }
        public string AMPHUR { get; set; }
        public string PROVINCE { get; set; }
        public string ZIPCODE { get; set; }
        public string PHONE { get; set; }
        public Nullable<int> NATION_ID { get; set; }
        public Nullable<int> PROFILE_TYPE { get; set; }
    
        public virtual TB_CUSTOMER TB_CUSTOMER { get; set; }
        public virtual TB_M_NATION TB_M_NATION { get; set; }
    }
}
