//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPU.DORMITORY.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_INVOICE_DETAIL
    {
        public int ID { get; set; }
        public int INVOICE_ID { get; set; }
        public Nullable<int> COST_TYPE_ID { get; set; }
        public Nullable<int> CUS_ID { get; set; }
        public Nullable<int> SPONSOR_ID { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string REMARK { get; set; }
    
        public virtual TB_INVOICE TB_INVOICE { get; set; }
        public virtual TB_M_COST_TYPE TB_M_COST_TYPE { get; set; }
    }
}
