//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPU.DORMITORY.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_INVOICE
    {
        public TB_INVOICE()
        {
            this.TB_INVOICE_DETAIL = new HashSet<TB_INVOICE_DETAIL>();
        }
    
        public int ID { get; set; }
        public Nullable<int> REF_ID { get; set; }
        public Nullable<System.DateTime> POSTING_DATE { get; set; }
        public string SAP_DOCNO { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<int> STAY_DAY { get; set; }
        public Nullable<bool> PAYMENT_STATUS { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> INVOICE_TYPE { get; set; }
        public string OTHER { get; set; }
        public Nullable<int> POST_TIME { get; set; }
    
        public virtual ICollection<TB_INVOICE_DETAIL> TB_INVOICE_DETAIL { get; set; }
    }
}
