//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPU.DORMITORY.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_INVOICE_DETAIL
    {
        public int ID { get; set; }
        public int INVOICE_ID { get; set; }
        public Nullable<int> SERVICE_ID { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<int> PAY_BY { get; set; }
        public Nullable<decimal> PAY_AMOUT { get; set; }
        public Nullable<int> COMPANY { get; set; }
        public Nullable<int> BA { get; set; }
        public Nullable<int> PROFIT_CTR { get; set; }
        public Nullable<int> MAIN_TRANS { get; set; }
        public Nullable<int> SUB_TRANS { get; set; }
    
        public virtual TB_INVOICE TB_INVOICE { get; set; }
        public virtual TB_M_SERVICE TB_M_SERVICE { get; set; }
    }
}
