//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPU.DORMITORY.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_BUILD
    {
        public TB_M_BUILD()
        {
            this.TB_M_SERVICE = new HashSet<TB_M_SERVICE>();
            this.TB_RATES_GROUP = new HashSet<TB_RATES_GROUP>();
            this.TB_ROOM = new HashSet<TB_ROOM>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BUILD_ID { get; set; }
        public string NAME { get; set; }
        public string COMPANY { get; set; }
        public string BA { get; set; }
        public string PROFIT_CTR { get; set; }
        public string TXT_NO { get; set; }
        public string DESCRIPTION { get; set; }
        public string DESCRIPTION_EN { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UDPATE_DATE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string ADDRESS_LINE_1 { get; set; }
        public string ADDRESS_LINE_2 { get; set; }
        public string ADDRESS_LINE_1_EN { get; set; }
        public string ADDRESS_LINE_2_EN { get; set; }
    
        public virtual ICollection<TB_M_SERVICE> TB_M_SERVICE { get; set; }
        public virtual ICollection<TB_RATES_GROUP> TB_RATES_GROUP { get; set; }
        public virtual ICollection<TB_ROOM> TB_ROOM { get; set; }
    }
}
