//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPU.DORMITORY.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_FUND
    {
        public TB_M_FUND()
        {
            this.TB_CUSTOMER_FUND = new HashSet<TB_CUSTOMER_FUND>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FOR_SERVICE_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ICollection<TB_CUSTOMER_FUND> TB_CUSTOMER_FUND { get; set; }
        public virtual TB_M_SERVICE TB_M_SERVICE { get; set; }
    }
}
