//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPU.DORMITORY.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_SERVICE
    {
        public int ID { get; set; }
        public Nullable<int> BUILD_ID { get; set; }
        public Nullable<int> COST_ID { get; set; }
        public Nullable<int> MAIN_TRANS { get; set; }
        public Nullable<int> SUB_TRANS { get; set; }
        public Nullable<int> GL_ACCOUNT { get; set; }
    
        public virtual TB_M_BUILD TB_M_BUILD { get; set; }
    }
}
