//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPU.DORMITORY.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_SERVICE
    {
        public TB_M_SERVICE()
        {
            this.TB_CUSTOMER_FUND = new HashSet<TB_CUSTOMER_FUND>();
            this.TB_INVOICE_DETAIL = new HashSet<TB_INVOICE_DETAIL>();
            this.TB_M_FUND = new HashSet<TB_M_FUND>();
            this.TB_RATES_GROUP_DETAIL = new HashSet<TB_RATES_GROUP_DETAIL>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string NAME_EN { get; set; }
    
        public virtual ICollection<TB_CUSTOMER_FUND> TB_CUSTOMER_FUND { get; set; }
        public virtual ICollection<TB_INVOICE_DETAIL> TB_INVOICE_DETAIL { get; set; }
        public virtual ICollection<TB_M_FUND> TB_M_FUND { get; set; }
        public virtual ICollection<TB_RATES_GROUP_DETAIL> TB_RATES_GROUP_DETAIL { get; set; }
    }
}
