//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPU.DORMITORY.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_CUSTOMER_TYPE
    {
        public TB_M_CUSTOMER_TYPE()
        {
            this.TB_CUSTOMER = new HashSet<TB_CUSTOMER>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<TB_CUSTOMER> TB_CUSTOMER { get; set; }
    }
}
