//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPU.DORMITORY.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ROOM
    {
        public TB_ROOM()
        {
            this.TB_ROOM_METER = new HashSet<TB_ROOM_METER>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BUILD_ID { get; set; }
        public Nullable<int> ROOM_TYPE_ID { get; set; }
        public Nullable<int> FLOOR { get; set; }
        public string NUMBER { get; set; }
        public Nullable<int> CUSTOMER_LIMIT { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> RATES_GROUP_ID { get; set; }
    
        public virtual TB_M_BUILD TB_M_BUILD { get; set; }
        public virtual TB_M_ROOM_TYPE TB_M_ROOM_TYPE { get; set; }
        public virtual TB_RATES_GROUP TB_RATES_GROUP { get; set; }
        public virtual ICollection<TB_ROOM_METER> TB_ROOM_METER { get; set; }
    }
}
