//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPU.DORMITORY.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ROOM_METER
    {
        public int ID { get; set; }
        public System.DateTime METER_DATE { get; set; }
        public Nullable<int> ROOM_ID { get; set; }
        public Nullable<int> METER_TYPE { get; set; }
        public Nullable<int> METER_START { get; set; }
        public Nullable<int> METER_END { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    
        public virtual TB_ROOM TB_ROOM { get; set; }
    }
}
