//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPU.DORMITORY.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_RATES_GROUP
    {
        public TB_RATES_GROUP()
        {
            this.TB_RATES_GROUP_DETAIL = new HashSet<TB_RATES_GROUP_DETAIL>();
            this.TB_ROOM = new HashSet<TB_ROOM>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BUILD_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> INSURANCE_AMOUNT { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    
        public virtual TB_M_BUILD TB_M_BUILD { get; set; }
        public virtual ICollection<TB_RATES_GROUP_DETAIL> TB_RATES_GROUP_DETAIL { get; set; }
        public virtual ICollection<TB_ROOM> TB_ROOM { get; set; }
    }
}
