//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPU.DORMITORY.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_RATES_GROUP_DETAIL
    {
        public int ID { get; set; }
        public int RATES_GROUP_ID { get; set; }
        public Nullable<int> SERVICE_ID { get; set; }
        public Nullable<int> MAINTRAN { get; set; }
        public Nullable<int> SUBTRAN { get; set; }
        public Nullable<int> GL { get; set; }
        public Nullable<int> UNIT { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<int> VAT { get; set; }
    
        public virtual TB_M_SERVICE TB_M_SERVICE { get; set; }
        public virtual TB_RATES_GROUP TB_RATES_GROUP { get; set; }
    }
}
