//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPU.DORMITORY.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TRANSFER_LOG
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> START_RUN_DATE { get; set; }
        public Nullable<System.DateTime> END_RUN_DATE { get; set; }
        public string RUN_STATUS { get; set; }
        public Nullable<int> TOTAL_ROW { get; set; }
        public Nullable<int> COMPLETE_ROW { get; set; }
        public Nullable<int> ERROR_ROW { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    
        public virtual TB_TRANSFER_REJECT_LOG TB_TRANSFER_REJECT_LOG { get; set; }
    }
}
