//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPU.DORMITORY.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS_LOGGED
    {
        public string USER_ID { get; set; }
        public string IP_ADDRESS { get; set; }
        public string SESSION_ID { get; set; }
        public System.DateTime LAST_SIGN_IN_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
