//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPU.DORMITORY.Biz.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public string USER_ID { get; set; }
        public string USER_PASSWORD { get; set; }
        public Nullable<int> TITLE_ID { get; set; }
        public Nullable<int> ROLE_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string PHONE_NO { get; set; }
        public string EXTENSION_NO { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<bool> IS_FORCE_CHANGE_PASSWORD { get; set; }
        public Nullable<System.DateTime> LAST_SIGN_IN_DATE { get; set; }
        public Nullable<System.DateTime> LAST_PWD_CHANGE_DATE { get; set; }
        public string PASSWORD_HISTORY_1 { get; set; }
        public string PASSWORD_HISTORY_2 { get; set; }
        public string PASSWORD_HISTORY_3 { get; set; }
        public string PASSWORD_HISTORY_4 { get; set; }
        public string PASSWORD_HISTORY_5 { get; set; }
        public Nullable<int> PASSWORD_COUNTER { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string RESPONSIBLE_BUIDING { get; set; }
    
        public virtual TB_M_TITLE TB_M_TITLE { get; set; }
        public virtual USERS_LOGGED USERS_LOGGED { get; set; }
        public virtual USER USERS1 { get; set; }
        public virtual USER USER1 { get; set; }
        public virtual USERS_ROLE USERS_ROLE { get; set; }
    }
}
